version: '3.9'
services:
  web:
    build: .
    command: bash -c 'pnpm install && pnpm run dev'
    ports:
      - '5173:5173'
    working_dir: '/app'
    expose:
      - '5173'
    volumes:
      - '.:/app'
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
    environment:
      - VITE_ENVIRONMENT=development
volumes:
  node_modules:
  pnpm-store:
